version: '3.5'
networks:
  Blog:
    external: false
services:
  blog-mysql:
    container_name: tutorial_db
    image: mysql
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    volumes:
      - './../dockerfile/mysql/data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: tutorial
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - '3307:3307'
    networks:
      - Blog
  blog-nginx:
    container_name: tutorial_nginx
    image: nginx
    restart: always
    volumes:
      - './:/var/www'
      - './docker/nginx:/etc/nginx/conf.d'
    ports:
      - '8081:80'
    networks:
      - Blog
  blog-php-fpm:
    container_name: tutorial_php
    build: docker/app
    volumes:
      - './:/var/www'
      - './docker/app/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini'
    ports:
      - '9001:9000' #менять порты на 9000:9000
    depends_on:
      - blog-mysql
    restart: unless-stopped
    networks:
      - Blog
